dist: bionic
language: generic

sudo: required

addons:
  apt:
    packages:
      - make
      - gcc
      - libpcre3-dev
      - libssl-dev
      - perl
      - build-essential
      - curl
      - zlib1g-dev
      - unzip
      - m4
      - libyaml-dev
      - valgrind
      - jq

before_install:
  - sudo service postgresql stop
  - sudo apt-get --yes remove postgresql-10-postgis-2.4
  - sudo apt install -yq --no-install-suggests --no-install-recommends postgresql-11-postgis-2.5-scripts postgresql-11 postgresql-client-11 postgresql-11-postgis-2.5
  - sed -e 's/^port.*/port = 5432/' /etc/postgresql/11/main/postgresql.conf > postgresql.conf
  - sudo chown postgres postgresql.conf
  - sudo mv postgresql.conf /etc/postgresql/11/main
  - sudo cp /etc/postgresql/{10,11}/main/pg_hba.conf
  - sudo service postgresql restart 11
before_script:
  - export PATH="/usr/lib/postgresql/11/bin:$PATH"
  - psql --version
  - psql -c 'create database kong;' -U postgres
  - psql -c "create user kong with encrypted password 'kong';" -U postgres
  - psql -c 'grant all privileges on database kong to kong;' -U postgres

after_success: |
  bash kong.sh
