dist: bionic
language: generic

sudo: required

addons:
  postgresql: "11.2"
  apt:
    packages:
      - make
      - gcc
      - libpcre3-dev
      - libssl-dev
      - perl
      - build-essential
      - curl
      - zlib1g-dev
      - unzip
      - m4
      - libyaml-dev
      - valgrind
      - jq

services:
  - postgresql

before_install:
  - sudo apt update
  - sudo apt -y remove postgresql-9.*\*
  - sudo apt -y remove postgresql-10.*\*
  - sudo apt install -yq --no-install-suggests --no-install-recommends postgresql-11 postgresql-client-11
  - sed -e 's/^port.*/port = 5432/' /etc/postgresql/11/main/postgresql.conf > postgresql.conf
  - sudo chown postgres postgresql.conf
  - sudo mv postgresql.conf /etc/postgresql/11/main
  - sudo cp /etc/postgresql/{10,11}/main/pg_hba.conf
  - sudo service postgresql restart 11
before_script:
  - export PATH="/usr/lib/postgresql/11/bin:$PATH"
  - psql --version
  - psql -c 'SELECT version();' -U postgres
  - psql -c 'CREATE USER kong;' -U postgres
  - psql -c 'CREATE DATABASE kong OWNER kong;' -U postgres

script:
  - bash kong.sh

notifications:
  slack: cyou-tech:1CImRdJdrBQMK7SW3lcyQDIx
