dist: bionic
language: generic

sudo: required

addons:
  apt:
    packages:
      - make
      - gcc
      - libpcre3-dev
      - libssl-dev
      - perl
      - build-essential
      - curl
      - zlib1g-dev
      - unzip
      - m4
      - libyaml-dev
      - valgrind
      - jq

services:
  - postgresql

before_script:
  - psql -c 'create database kong;' -U postgres
  - psql -c "create user kong with encrypted password 'kong';" -U postgres
  - psql -c 'grant all privileges on database kong to kong;' -U postgres

after_success: |
  bash kong.sh
